# Generated by Django 4.0.6 on 2023-01-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='listing_bid',
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_image',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
