# Generated by Django 4.0.6 on 2023-01-28 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_bid_bid_listing_bid_bid_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_watchlist',
            field=models.ManyToManyField(blank=True, related_name='wachtlist_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
