# Generated by Django 4.0.6 on 2023-01-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_listing_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_open',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
