# Generated by Django 4.0.6 on 2023-01-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_listing_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
