# Generated by Django 4.0.6 on 2023-01-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_listing_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
