# Generated by Django 4.0.6 on 2023-01-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_description',
            field=models.CharField(max_length=500),
        ),
    ]
